# Generated by Django 2.1.7 on 2019-12-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_image')),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('area', models.IntegerField()),
                ('build_yr', models.IntegerField()),
                ('notes', models.TextField(max_length=200)),
                ('tax_applicable', models.BooleanField(default=False)),
                ('estimated_payment', models.IntegerField()),
                ('vr_url', models.CharField(max_length=500)),
                ('aerial_video_url', models.CharField(max_length=500)),
                ('satellite_img', models.ImageField(upload_to='satellite_image')),
                ('google_map_url', models.CharField(max_length=500)),
                ('listing_owner', models.CharField(max_length=500)),
                ('listing_agent', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('C/S', 'Coming Soon'), ('ACT', 'Active'), ('CLS', 'Closed')], max_length=1)),
                ('brochure', models.FileField(upload_to='brochure')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property'),
        ),
    ]
