# Generated by Django 2.1.7 on 2019-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('C/S', 'Coming Soon'), ('ACT', 'Active'), ('CLS', 'Closed')], max_length=3),
        ),
    ]
