# Generated by Django 2.1.7 on 2019-12-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191206_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(),
        ),
    ]
