# Generated by Django 2.1.7 on 2019-12-07 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191207_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='display_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='display_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='heading',
            field=models.CharField(default=333333, max_length=250),
            preserve_default=False,
        ),
    ]
