# Generated by Django 2.1.7 on 2019-12-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191207_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Coming Soon', 'Coming Soon'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=3),
        ),
    ]
