# Generated by Django 2.1.7 on 2019-12-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20191216_2243'),
        ('home', '0006_auto_20191207_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='agents.agents'),
            preserve_default=False,
        ),
    ]
